### ISSUE TITLE
Add reload support for data changes

### ISSUE THREAD

**Issue by bberberoglu** [adessoTurkey-dotNET/NLocalizator#4]
This library should reload itself when localization data changed. For these feature we can use file watcher or IOptions approach. This will be great feature because after data changes applications doesn't need to restart.

**Comment by tolgacakir** [comment]
NLocalizator already provides the data changes with file watcher. You can check [this](https://github.com/adessoTurkey-dotNET/NLocalizator/blob/main/src/NLocalizator/Localizator.cs#L13)

In this situation, the applications doesn't need to restart.

But I am not sure about configuration file. Maybe we can to allow configuration changes in run-time with IOptions, IOptionsMonitor etc.

For this, we need to configure the Localizator from appsettings.json file.

**Comment by bberberoglu** [comment]
Thanks for explanation, I missed it. But IOptions and Custom Configuration Provider is important as you mentioned

**Comment by bberberoglu** [comment]
Thanks for explanation, I missed it. But IOptions and Custom Configuration Provider is important as you mentioned
